name: Docker Publish

on:
  push:
    branches: [main]

jobs:
  push-image-to-registry:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/landingpage-frontend:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/landingpage-frontend:latest
